name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [12]
        script: ["test:ci"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache dependencies
        id: node-module-cache
        uses: actions/cache@v2
        env:
          cache-name: node-module-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-ci-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock', './yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-ci-${{ env.cache-name }}-
      - name: Install packages
        run: yarn --immutable
      - name: Run integration tests
        run: yarn ${{ matrix.script }}
